
### Variables
@port = 3000


### Get todos

GET http://localhost:{{port}}/api/todos
                       
### Create a todo

POST http://localhost:{{port}}/api/todos
Content-Type: application/json

{
  "item": "Finish the Assignment"
}

### Toggle completed status of a todo

### Toggle Works to set it in here but when I try to do it from the checkbox it dont work
PUT http://localhost:{{port}}/api/todos/6621426738833aa8b21e8fd4


